### ISSUE TITLE
CTS failing for xtdb (xtdb 3.15, egeria 3.15/main)

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria-connector-xtdb#464]
CTS test 
 - Egeria '3.15'
  - xtdb 3.15
  - Large openshift cluster
  
  Config:
  ```
  # SPDX-License-Identifier: CC-BY-4.0
# Copyright Contributors to the ODPi Egeria project.
tut:
  serverType: "plugin"
  connectorProvider: "org.odpi.egeria.connectors.juxt.xtdb.repositoryconnector.XtdbOMRSRepositoryConnectorProvider"
  connectorConfig:
    xtdbConfig:
      xtdb/index-store:
        kv-store:
          xtdb/module: xtdb.lmdb/->kv-store
          db-dir: data/servers/xtdb/lmdb-index
      xtdb/document-store:
        kv-store:
          xtdb/module: xtdb.rocksdb/->kv-store
          db-dir: data/servers/xtdb/rdb-docs
      xtdb/tx-log:
        kv-store:
          xtdb/module: xtdb.rocksdb/->kv-store
          db-dir: data/servers/xtdb/rdb-tx
      xtdb.lucene/lucene-store:
        db-dir: data/servers/xtdb/lucene
downloads:
  - filename: egeria-connector-xtdb.jar
    url: "http://repository.sonatype.org/service/local/artifact/maven/redirect?r=central-proxy&g=org.odpi.egeria&a=egeria-connector-xtdb&v=RELEASE&c=jar-with-dependencies"
    #url: "http://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.odpi.egeria&a=egeria-connector-xtdb&v=3.15-SNAPSHOT&c=jar-with-dependencies"
    ```
    
    Results
    ```
                  Metadata sharing MANDATORY_PROFILE    CONFORMANT_FULL_SUPPORT [  67066 /      0 ]
              Reference copies  OPTIONAL_PROFILE             NOT_CONFORMANT [    535 /    116 ]
          Metadata maintenance  OPTIONAL_PROFILE             NOT_CONFORMANT [      0 /    651 ]
                 Dynamic types  OPTIONAL_PROFILE             UNKNOWN_STATUS [      0 /      0 ]
                 Graph queries  OPTIONAL_PROFILE             NOT_CONFORMANT [      0 /      1 ]
             Historical search  OPTIONAL_PROFILE             UNKNOWN_STATUS [      0 /      0 ]
                Entity proxies  OPTIONAL_PROFILE             NOT_CONFORMANT [      0 /    238 ]
       Soft-delete and restore  OPTIONAL_PROFILE             UNKNOWN_STATUS [      0 /      0 ]
                Undo an update  OPTIONAL_PROFILE             UNKNOWN_STATUS [      0 /      0 ]
           Reidentify instance  OPTIONAL_PROFILE             NOT_CONFORMANT [      0 /    535 ]
               Retype instance  OPTIONAL_PROFILE             NOT_CONFORMANT [      0 /    297 ]
               Rehome instance  OPTIONAL_PROFILE             UNKNOWN_STATUS [      0 /      0 ]
                 Entity search  OPTIONAL_PROFILE             NOT_CONFORMANT [      0 /    594 ]
           Relationship search  OPTIONAL_PROFILE             NOT_CONFORMANT [      0 /    238 ]
        Entity advanced search  OPTIONAL_PROFILE             UNKNOWN_STATUS [      0 /      0 ]
  Relationship advanced search  OPTIONAL_PROFILE             UNKNOWN_STATUS [      0 /      0 ]
List the versions of each instance  OPTIONAL_PROFILE             UNKNOWN_STATUS [      0 /      0 ]
Store classifications independently of entity  OPTIONAL_PROFILE             UNKNOWN_STATUS [      0 /      0 ]
            External instances  OPTIONAL_PROFILE             UNKNOWN_STATUS [      0 /      0 ]
Restore metadata from a backup  OPTIONAL_PROFILE             UNKNOWN_STATUS [      0 /      0 ]

FAIL [67601/2670]
```

Also the automated cts at https://github.com/odpi/egeria-test-cts/actions is currently failing (this uses 'main')
See https://github.com/odpi/egeria-test-cts/actions

Specifically the latest test run shows identical results to above https://github.com/odpi/egeria-test-cts/actions/runs/4249004030

cc: @cmgrote @mandy-chessell
